name: build

on:
  push:
  # Temporarily disable this action
  # See https://github.community/t/how-can-i-disable-a-github-action/17049
  # branches-ignore:
  #   - "**"
  schedule:
    # * is a special character in YAML so you have to quote this string
    # At 05:00 on Sunday
    # https://crontab.guru/#0_5_*_*_0
    - cron: "0 4 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: getong/mariadb-action@v1.1
        with:
          character set server: 'utf8mb4' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8mb4_unicode_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mariadb version: '10.4.10' # Optional, default value is "latest". The version of the MariaDB
      - name: Build with Maven
        run: ./mvnw clean -DskipTests=false -Dmaven.javadoc.skip=true -B -V install
