name: build

on:
  push:
  # Temporarily disable this action
  # See https://github.community/t/how-can-i-disable-a-github-action/17049
  # branches-ignore:
  #   - "**"
  schedule:
    # * is a special character in YAML so you have to quote this string
    # At 05:00 on Sunday
    # https://crontab.guru/#0_5_*_*_0
    - cron: "0 4 * * 0"

env:
  DATABASE_PASSWORD: myPassword


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it

      - name: Run MariaDB
        run: |
          docker run -d -e MARIADB_ROOT_PASSWORD=${{ env.DATABASE_PASSWORD }} -p3306:3306 mariadb;

      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Verify MariaDB connection
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"3306" --silent; do
            sleep 1
          done

      - name: Build with Maven
        run: ./mvnw clean -DskipTests=false -Dmaven.javadoc.skip=true -B -V install
